// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfwdcIXtnoBnmJEnXZpFN0XarTnAh26UE',
    appId: '1:51722730670:web:f5c1a4323e3fe03af5413f',
    messagingSenderId: '51722730670',
    projectId: 'attendance-2da0f',
    authDomain: 'attendance-2da0f.firebaseapp.com',
    storageBucket: 'attendance-2da0f.firebasestorage.app',
    measurementId: 'G-K1VPDY62H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBKirckJvnaHdC2PeZHcTZKLBV8n5j-gE',
    appId: '1:51722730670:android:ac3b7b342891619ef5413f',
    messagingSenderId: '51722730670',
    projectId: 'attendance-2da0f',
    storageBucket: 'attendance-2da0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa_-ezYQqwsIa7F4g2EKIqrd90mwF6bDE',
    appId: '1:51722730670:ios:109f43d9c77c65def5413f',
    messagingSenderId: '51722730670',
    projectId: 'attendance-2da0f',
    storageBucket: 'attendance-2da0f.firebasestorage.app',
    iosBundleId: 'com.example.attendance',
  );
}
